services:

  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USUARIO}
      MONGO_INITDB_ROOT_PASSWORD: ${SENHA}
    volumes:
      - ./mongo/db/:/data/db
      - ./mongo/configdb/:/data/configdb

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    hostname: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${USUARIO}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${SENHA}
      ME_CONFIG_MONGODB_URL: mongodb://${USUARIO}:${SENHA}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  
  backend:
    image: python:latest
    container_name: backend
    hostname: backend
    restart: always
    command: tail -f /dev/null
    volumes:
      - ./backend:/app
    ports:
      - 5000:5000
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${USUARIO}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${SENHA}
      ME_CONFIG_MONGODB_URL: mongodb://${USUARIO}:${SENHA}@mongo:27017/
    depends_on:
      - mongo